### ISSUE TITLE
Track Edit Window in Client shows up unexpected

### ISSUE THREAD

**Issue by Mellich** [Mellich/JukePi#18]
The Edit Track window of the client shows up everytime the gaplist is updated, althought it was not requested to,

**Comment by Haeldeus** [comment]
May have been fixed by the last update, but has to be tested.

**Comment by Mellich** [comment]
Still appears when a track ends regulary and a new track starts
